import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import {
  FeatureLandingScreenshot,
  Footer,
  HeroSplitImage,
  TestimonialsLargeAvatar
  
} from "../components"

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>All Beauty By K Marie</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        < HeroSplitImage />
        <FeatureLandingScreenshot />
        <TestimonialsLargeAvatar />
        <Footer />
      </main>
    </>
  );
};

export default Home;
